LOAD DATA LOCAL INFILE "regular.dat"
INTO TABLE Regular
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "moderator.dat"
INTO TABLE Moderator
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "question.dat"
INTO TABLE Question
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "quiz.dat"
INTO TABLE Quiz
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "answer.dat"
INTO TABLE Answer
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "appears_in.dat"
INTO TABLE Appears_in
FIELDS TERMINATED BY "<>";
